// <auto-generated />
namespace Garage2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Parkinglot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Parkinglot));
        
        string IMigrationMetadata.Id
        {
            get { return "201601201521252_Parkinglot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
